Output demo.gif

Set WindowBar Colorful
Set FontSize 15
Set Width 1280
Set Height 720

Set TypingSpeed 200ms
Set PlaybackSpeed 1

Type ssex
Sleep 1.5
Enter

Type "123.123.123.123"
Sleep 500ms
Enter

Type "22"
Sleep 500ms
Enter

Type "root"
Sleep 1
Enter

Set TypingSpeed 200ms
Set PlaybackSpeed 1.5
Sleep 5

Set TypingSpeed 300ms
Set PlaybackSpeed 1.5

Sleep 1
Type "ls -tla"
Enter
Sleep 1

Type "touch test.txt"
Enter
Sleep 1

Type "ls -tla"
Enter
Sleep 1

Type "ps -ef | head"
Enter
Sleep 4

